---
- name: Reload SystemD Daemon
  ansible.builtin.shell:
    cmd: systemctl daemon-reload
  listen: daemon-reload

- name: "Restart {{ __service_name | capitalize }} quadlet container"
  ansible.builtin.service:
    name: "{{ __service_name }}"
    state: restarted
  listen: quadlet-restart
